#!/usr/bin/env ruby

NAME = 'swiftiply'
CONFIG="/etc/#{NAME}.yml"

require 'rubygems'
require 'daemons'

script_args = false
daemon_args = ARGV.find_all {|e|
  script_args = true if e == '--'
  !script_args
}

options = {
  :app_name   => NAME,
  :ARGV       => daemon_args + ['--', '--config', CONFIG, '--daemonize', 'n'],
  :dir_mode   => :system,
  :multiple   => false,
  :ontop      => false,
  :mode       => :exec,
  :monitor    => false
}

Daemons.run("/usr/bin/#{NAME}", options)