--- 
address: 127.0.0.1
port: 8001
servers: 2
timeout: 30
max_conns: 1024
environment: production
max_persistent_conns: 512
daemonize: true
swiftiply: true
adapter: rails
user: deploy
group: deploy
pid: tmp/pids/thin.pid
log: log/thin.log